// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrsxsrjpeuxfyrdlgjbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlyc3hzcmpwZXV4ZnlyZGxnamJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyODAzMjMsImV4cCI6MjA3MTg1NjMyM30.rfFRdww2ufSvtAZr1_rHkB-z5WZHpTPByzAFYQIQP0w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});